### ISSUE TITLE
Anqi Zhou's Speaker Proposal

### ISSUE THREAD

**Issue by Anqi-Zhou** [uchicago-computation-workshop/fall2019mixer#63]
There are so many world-wide famous professors in Uchicago that I respect a lot. I really wish some of them could give us inspiring speeches, such as the Nobel Prize Winner Fama French and the like.

As for non-Uchicago speaker, I think we would be extremely excited if you are able to invite former president Obama. Hyde Park neighborhood is very proud of President Obama. It may be not so uncommon that President Obama give speech in Uchicago? I'm not sure...

I would like to hear topics related to macroeconomics or political economics, which I find very interesting.

**Comment by smiklin** [comment]
Dear Anqi,
Please repost this as three separate issues, as other students are doing!

**Comment by Anqi-Zhou** [comment]
Dear Sanja,

I have submitted another two issues. Sorry for the inconvenience... I didn't notice the requirements carefully...

Wish you all the best.

Sincerely,

Anqi Zhou
________________________________
发件人: Sanja Miklin <notifications@github.com>
发送时间: 2019年10月4日 22:49
收件人: uchicago-computation-workshop/fall2019mixer <fall2019mixer@noreply.github.com>
抄送: Anqi Zhou <anqiz1@uchicago.edu>; Author <author@noreply.github.com>
主题: Re: [uchicago-computation-workshop/fall2019mixer] Anqi Zhou's Speaker Proposal (#63)


Dear Anqi,
Please repost this as three separate issues, as other students are doing!

―
